# Generated by Django 6.0.3 on 2026-04-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_consultation_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_slot',
        ),
    ]
