# Generated by Django 6.0.3 on 2026-04-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(default='ONLINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default='TEMP_ID', help_text='Kashier Transaction ID', max_length=100),
            preserve_default=False,
        ),
    ]
