# Generated by Django 6.0.3 on 2026-04-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_paymenttransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='kashier_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
